[package]
name = "eth_audit_unchecked_send"
version = "0.1.0"
edition = "2021"

[dependencies]
eth_audit_core = { path = "../eth_audit_core" }
solang-parser = "0.3.5"
serde = { version = "1", features = ["derive"] }

